name: Deploy

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subproject:
          - directflux
          - adapter
          - engine
          - event

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'liberica'
        cache: maven
    - name: Test Deploy (dry run)
      run: mvn -pl ${{ matrix.subproject }} clean deploy -DaltDeploymentRepository=github::default::file:/tmp/alt-repo  --batch-mode --update-snapshots --no-transfer-progress --file pom.xml -DskipTests -Dmaven.test.skip=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      run: mvn -pl ${{ matrix.subproject }} deploy --batch-mode --update-snapshots --no-transfer-progress --file pom.xml -DskipTests -Dmaven.test.skip=true
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
